# Selected portable/divopt implementation, ordered for compilation.
rtl/portable/arithmetic/asic_signed_multiplier.v
rtl/portable/arithmetic/mult_div.v
rtl/portable/arithmetic/asic_complex_multiplier.v
rtl/portable/arithmetic/RLS12_mult.v
rtl/portable/arithmetic/RLS12_R2_mult.v
rtl/portable/arithmetic/asic_reloadable_fir.v
rtl/portable/arithmetic/RLS12_c_fir_im1.v
rtl/optimized/arithmetic/asic_signed_fractional_divider_radix4_exact.v
rtl/optimized/arithmetic/asic_signed_fractional_divider_radix4_aligned.v
rtl/optimized/arithmetic/float_complex_div_divopt.v
rtl/portable/memory/asic_shift_delay.v
rtl/portable/memory/RLS12_delay_coe_pluse.v
rtl/portable/memory/RLS12_delay_rd.v
rtl/portable/memory/asic_sync_fifo.v
rtl/portable/memory/RLS12_rx_fifo.v
rtl/portable/memory/asic_pack_sync_fifo.v
rtl/portable/memory/RLS12_pack_fifo.v
rtl/portable/memory/fifo_RLS12_c_rx.v
rtl/portable/memory/asic_sdp_sram.v
rtl/portable/memory/RLS12_c_pack_ram_fb.v
rtl/portable/memory/RLS12_Pram.v
rtl/portable/memory/packto121.v
rtl/portable/core/RLS12_c_data_pack_fb.v
rtl/portable/core/RLS12_c_data_pack_fb2.v
rtl/portable/core/RLS12_c_data_pack_rx.v
rtl/optimized/core/RLS12_c_matrixP_update_divopt.v
rtl/portable/core/RLS12_c_rls_fir3_out_new.v
rtl/optimized/top/RLS12_c_MW_core_divopt.v
rtl/portable/interfaces/asic_reset_sync_2ff.v
rtl/optimized/top/RLS12_c_MW_top_divopt.v
